-- ============================================================
-- AaraPartner Feature Migration
-- ============================================================

-- 1. Extend profiles user_type to include ara_partner and admin
ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_user_type_check;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_user_type_check
  CHECK (user_type IN ('landlord', 'tenant', 'manager', 'ara_partner', 'admin'));

-- 2. ara_partners — extended profile for AaraPartner users
CREATE TABLE IF NOT EXISTS public.ara_partners (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name           TEXT NOT NULL,
  phone               TEXT,
  payment_method      TEXT NOT NULL DEFAULT 'etransfer' CHECK (payment_method IN ('etransfer', 'bank')),
  etransfer_id        TEXT,
  bank_transit        TEXT,
  bank_routing        TEXT,
  bank_account        TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. referrals — one per unique property address
CREATE TABLE IF NOT EXISTS public.referrals (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ara_partner_id      UUID NOT NULL REFERENCES public.ara_partners(id) ON DELETE CASCADE,
  landlord_name       TEXT NOT NULL,
  landlord_phone      TEXT,
  landlord_email      TEXT,
  property_address    TEXT NOT NULL UNIQUE,
  status              TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  subscription_fee    NUMERIC(10,2),
  notes               TEXT,
  approved_at         TIMESTAMPTZ,
  approved_by         UUID REFERENCES auth.users(id),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. commission_rules — per referral, supports rate history
CREATE TABLE IF NOT EXISTS public.commission_rules (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  referral_id         UUID NOT NULL REFERENCES public.referrals(id) ON DELETE CASCADE,
  commission_percent  NUMERIC(5,2) NOT NULL CHECK (commission_percent > 0 AND commission_percent <= 100),
  start_date          DATE NOT NULL,
  end_date            DATE,
  created_by          UUID REFERENCES auth.users(id),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. payout_records — generated by monthly batch
CREATE TABLE IF NOT EXISTS public.payout_records (
  id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ara_partner_id              UUID NOT NULL REFERENCES public.ara_partners(id) ON DELETE CASCADE,
  referral_id                 UUID NOT NULL REFERENCES public.referrals(id) ON DELETE CASCADE,
  payout_month                DATE NOT NULL,
  subscription_fee_snapshot   NUMERIC(10,2) NOT NULL,
  commission_percent_snapshot NUMERIC(5,2) NOT NULL,
  amount                      NUMERIC(10,2) NOT NULL,
  payment_method_snapshot     TEXT NOT NULL,
  etransfer_id_snapshot       TEXT,
  bank_details_snapshot       JSONB,
  status                      TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'paid', 'cancelled')),
  paid_at                     TIMESTAMPTZ,
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (referral_id, payout_month)
);

-- 6. audit_log — track admin changes
CREATE TABLE IF NOT EXISTS public.audit_log (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type   TEXT NOT NULL,
  entity_id     UUID NOT NULL,
  action        TEXT NOT NULL,
  changed_by    UUID REFERENCES auth.users(id),
  old_values    JSONB,
  new_values    JSONB,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- Indexes
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_referrals_ara_partner ON public.referrals(ara_partner_id);
CREATE INDEX IF NOT EXISTS idx_referrals_status ON public.referrals(status);
CREATE INDEX IF NOT EXISTS idx_commission_rules_referral ON public.commission_rules(referral_id);
CREATE INDEX IF NOT EXISTS idx_payout_records_partner ON public.payout_records(ara_partner_id);
CREATE INDEX IF NOT EXISTS idx_payout_records_month ON public.payout_records(payout_month);
CREATE INDEX IF NOT EXISTS idx_audit_log_entity ON public.audit_log(entity_type, entity_id);

-- ============================================================
-- Updated_at triggers
-- ============================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER ara_partners_updated_at
  BEFORE UPDATE ON public.ara_partners
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER referrals_updated_at
  BEFORE UPDATE ON public.referrals
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- Row Level Security
-- ============================================================
ALTER TABLE public.ara_partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commission_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payout_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

-- ara_partners: own row only
CREATE POLICY "ara_partners_self" ON public.ara_partners
  FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "ara_partners_admin" ON public.ara_partners
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND user_type = 'admin')
  );

-- referrals: AaraPartner sees own, admin sees all
CREATE POLICY "referrals_own" ON public.referrals
  FOR ALL USING (
    ara_partner_id IN (SELECT id FROM public.ara_partners WHERE user_id = auth.uid())
  );

CREATE POLICY "referrals_admin" ON public.referrals
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND user_type = 'admin')
  );

-- commission_rules: AaraPartner reads own referral rules, admin full access
CREATE POLICY "commission_rules_read_own" ON public.commission_rules
  FOR SELECT USING (
    referral_id IN (
      SELECT r.id FROM public.referrals r
      JOIN public.ara_partners ap ON ap.id = r.ara_partner_id
      WHERE ap.user_id = auth.uid()
    )
  );

CREATE POLICY "commission_rules_admin" ON public.commission_rules
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND user_type = 'admin')
  );

-- payout_records: AaraPartner reads own, admin full access
CREATE POLICY "payout_records_read_own" ON public.payout_records
  FOR SELECT USING (
    ara_partner_id IN (SELECT id FROM public.ara_partners WHERE user_id = auth.uid())
  );

CREATE POLICY "payout_records_admin" ON public.payout_records
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND user_type = 'admin')
  );

-- audit_log: admin only
CREATE POLICY "audit_log_admin" ON public.audit_log
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND user_type = 'admin')
  );
